blank_issues_enabled: false
contact_links:
  - name: ⚠️ Application issue
    url: https://github.com/kodjodevf/mangayomi/issues/new/choose
    about: Issues and requests about the app itself should be opened in the mangayomi repository instead
  - name: Mangayomi app GitHub repository
    url: https://github.com/kodjodevf/mangayomi
    about: Issues about the app itself should be opened here instead.
